name: Android Release
run-name: ${{ format('Release version {0}', inputs.version)}} by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version (without v)'
        required: true
        type: string

      snapshot:
        description: 'Next SNAPSHOT version (without v). Defaults to current value'
        required: false
        type: string

      deploy-github:
        description: 'Deploy build to GitHub'
        default: false
        type: boolean
        required: false

      deploy-maven:
        description: 'Deploy build to Maven'
        default: false
        type: boolean
        required: false

      decrypt-secrets:
        description: 'Whether there are secrets that need to be decrypted before release'
        default: false
        type: boolean
        required: false

      release_assets:
        description: 'Newline-delimited list of path globs for asset files to upload as part of the GitHub release'
        type: string
        required: false
    secrets:
      ORG_GRADLE_PROJECT_OPEN_PASS_RELEASE_KEYSTORE_PWD:
        required: false
      ORG_GRADLE_PROJECT_OPEN_PASS_RELEASE_KEY_PWD:
        required: false
      ENCRYPT_KEY:
        required: false
      RELEASE_VERSION_BOT_PRIVATE_KEY:
        required: false
      CENTRAL_SONATYPE_MAVEN_ACCOUNT_USERNAME:
        required: false
      CENTRAL_SONATYPE_MAVEN_ACCOUNT_PASSWORD:
        required: false
      MAVEN_GPG_SIGNING_KEY:
        required: false
      MAVEN_GPG_SIGNING_PASSPHRASE:
        required: false

jobs:
  publish:
    name: Android Release
    runs-on: ubuntu-latest
    env:
      ORG_GRADLE_PROJECT_OPEN_PASS_RELEASE_KEYSTORE_PWD: ${{ secrets.ORG_GRADLE_PROJECT_OPEN_PASS_RELEASE_KEYSTORE_PWD }}
      ORG_GRADLE_PROJECT_OPEN_PASS_RELEASE_KEY_PWD: ${{ secrets.ORG_GRADLE_PROJECT_OPEN_PASS_RELEASE_KEY_PWD }}

    permissions:
      id-token: write
      contents: write
      packages: write

    steps:
      - name: Generate build number
        shell: bash
        run: echo "ORG_GRADLE_PROJECT_OPEN_PASS_VERSION_CODE=$(( $GITHUB_RUN_NUMBER + 10000 ))" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update Git user
        run: |
          git config --local user.name "openpass-sso"
          git config --local user.email openpass-sso@users.noreply.github.com

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1
        with:
          cache-disabled: true

      - name: Decrypt secrets
        if: ${{ inputs.decrypt-secrets == true }}
        run: ./scripts/decrypt-secrets.sh
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

      - name: Get Snapshot versions
        id: snapshot-versions
        run: ./scripts/get_snapshot_versions.sh "${INPUTS_SNAPSHOT}"
        env:
          INPUTS_SNAPSHOT: ${{ inputs.snapshot }}

      - name: Update Gradle properties
        shell: bash
        run: |
          sed -i.bak "s/${CUR_SNAPSHOT_VERSION}/${INPUTS_VERSION}/g" gradle.properties
        env:
          CUR_SNAPSHOT_VERSION: ${{ steps.snapshot-versions.outputs.cur_snapshot_version }}
          INPUTS_VERSION: ${{ inputs.version }}

      - name: Commit Gradle properties
        run: |
          git add gradle.properties
          git commit -m "Prepare for release: ${INPUTS_VERSION}"
        env:
          INPUTS_VERSION: ${{ inputs.version }}

      - name : Build Locally
        run: ./gradlew build

      - name: Deploy v${{ inputs.version }} (GitHub)
        if: ${{ inputs.deploy-github == true }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ github.token }}

      - name: Deploy v${{ inputs.version }} (Maven)
        if: ${{ inputs.deploy-maven == true }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_SONATYPE_MAVEN_ACCOUNT_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_SONATYPE_MAVEN_ACCOUNT_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_GPG_SIGNING_PASSPHRASE }}

      - name: Tag release
        run: |
          git tag "v${INPUTS_VERSION}"
        env:
          INPUTS_VERSION: ${{ inputs.version }}

      - name: Update Gradle properties (Snapshot)
        shell: bash
        run: |
          sed -i.bak "s/${INPUTS_VERSION}/${NEW_SNAPSHOT_VERSION}/g" gradle.properties
        env:
          INPUTS_VERSION: ${{ inputs.version }}
          NEW_SNAPSHOT_VERSION: ${{ steps.snapshot-versions.outputs.new_snapshot_version }}

      - name: Commit Gradle properties (Snapshot)
        run: |
          git add gradle.properties
          git commit -m "Prepare next development version: ${NEW_SNAPSHOT_VERSION}"
        env:
          NEW_SNAPSHOT_VERSION: ${{ steps.snapshot-versions.outputs.new_snapshot_version }}

      - name: Cleanup
        shell: bash
        run: |
          rm gradle.properties.bak

      - name: Authenticate using Release Version GitHub App
        id: auth
        uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1.9.0
        with:
          app_id: ${{ vars.RELEASE_VERSION_BOT_APP_ID }}
          private_key: ${{ secrets.RELEASE_VERSION_BOT_PRIVATE_KEY }}

      - name: Push changes
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # master on Jul 1, 2024
        with:
          branch: ${{ github.ref }}
          github_token: ${{ steps.auth.outputs.token }}

      - name: Push changes to tag
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa # master on Jul 1, 2024
        with:
          branch: ${{ github.ref }}
          tags: true
          push_only_tags: true

      - name: GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: ${{ inputs.release_assets }}
          generate_release_notes: true
          tag_name: v${{ inputs.version }}
