name: Build

on:
  workflow_call:
    inputs:
      deploy-snapshot-github:
        description: 'Deploy Snapshot build to GitHub'
        default: false
        type: boolean
        required: false

      deploy-snapshot-maven:
        description: 'Deploy Snapshot build to Maven'
        default: false
        type: boolean
        required: false
    secrets:
      CENTRAL_SONATYPE_MAVEN_ACCOUNT_USERNAME:
        required: false
      CENTRAL_SONATYPE_MAVEN_ACCOUNT_PASSWORD:
        required: false
      MAVEN_GPG_SIGNING_KEY:
        required: false
      MAVEN_GPG_SIGNING_PASSPHRASE:
        required: false

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      - name: Build and run tests
        run: ./gradlew spotlessCheck build

      - name: Deploy SNAPSHOT to GitHub Packages
        if: ${{ inputs.deploy-snapshot-github == true }}
        run: ./gradlew publish --stacktrace
        env:
          ORG_GRADLE_PROJECT_githubPackagesUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesPassword: ${{ github.token }}

      - name: Deploy SNAPSHOT to Maven Central
        if: ${{ inputs.deploy-snapshot-maven == true }}
        run: ./gradlew publish --stacktrace
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_SONATYPE_MAVEN_ACCOUNT_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_SONATYPE_MAVEN_ACCOUNT_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_GPG_SIGNING_PASSPHRASE }}
