name: Publish

on:
  release:
    types: [published, edited]

jobs:
  build-browserstack-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install deps and build
        run: |
          cd actions/browserstack
          npm ci && npm run build --if-present

      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
